# ============================================================
# pollinations_client.py — Free cloud image generation
#
# Pollinations.ai is a completely free, no-auth-required image
# generation service. Images are generated by making a simple
# HTTP GET request — no GPU, no API key, no cost.
#
# Supported models (IMAGE_GEN_MODEL setting):
#   flux          — Flux.1-dev (best quality, default)
#   flux-realism  — Flux photorealistic variant
#   flux-anime    — Anime / illustrated style
#   flux-3d       — 3D render style
#   turbo         — SDXL-Turbo (fastest, lower quality)
#
# API docs: https://pollinations.ai/
# ============================================================

import logging
import aiohttp
from pathlib import Path
from urllib.parse import quote

logger = logging.getLogger(__name__)

POLLINATIONS_BASE_URL = "https://image.pollinations.ai/prompt"


async def generate_image_pollinations(
    character_name: str,
    prompt: str,
    output_dir: str,
    model: str = "flux",
    width: int = 1024,
    height: int = 1024,
    seed: int | None = None,
    timeout: float = 90.0,
) -> str:
    """
    Generate a character portrait via Pollinations.ai.

    Sends a single HTTP GET request and writes the returned image to disk.
    Free, no API key required, works on any hardware.

    Args:
        character_name:  Used to derive the output filename.
        prompt:          Full text prompt for the image.
        output_dir:      Directory to save the PNG into.
        model:           Pollinations model name (default: "flux").
        width, height:   Image dimensions in pixels (default: 1024×1024).
        seed:            Optional seed for reproducibility.
        timeout:         HTTP timeout in seconds.

    Returns:
        Absolute path to the saved PNG file.

    Raises:
        RuntimeError: If the API call fails or returns a non-200 status.
    """
    # Build the request URL
    encoded_prompt = quote(prompt, safe="")
    params  = f"?width={width}&height={height}&model={model}&nologo=true&enhance=false"
    if seed is not None:
        params += f"&seed={seed}"

    url = f"{POLLINATIONS_BASE_URL}/{encoded_prompt}{params}"
    logger.info("[Pollinations] Requesting: model=%s | character=%s", model, character_name)
    logger.debug("[Pollinations] URL: %s", url)

    # Prepare output path
    safe_name = character_name.strip().replace(" ", "_").replace("/", "_")
    out_dir   = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    img_path  = out_dir / f"{safe_name}.png"

    async with aiohttp.ClientSession() as session:
        async with session.get(
            url,
            timeout=aiohttp.ClientTimeout(total=timeout),
            headers={"User-Agent": "WritersRoom/1.0"},
        ) as resp:
            if resp.status != 200:
                body = await resp.text()
                raise RuntimeError(
                    f"Pollinations API returned HTTP {resp.status}: {body[:200]}"
                )
            img_bytes = await resp.read()

    if len(img_bytes) < 1000:
        raise RuntimeError(
            f"Pollinations returned suspiciously small response ({len(img_bytes)} bytes) "
            f"— likely an error page, not an image."
        )

    img_path.write_bytes(img_bytes)
    logger.info("[Pollinations] Saved %d bytes → %s", len(img_bytes), str(img_path))
    return str(img_path.resolve())


async def check_pollinations_reachable(timeout: float = 5.0) -> bool:
    """Quick reachability check for the Pollinations.ai API."""
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(
                "https://image.pollinations.ai/",
                timeout=aiohttp.ClientTimeout(total=timeout),
            ) as resp:
                return resp.status < 500
    except Exception:
        return False
